[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["Lending"]

remappings = ["@openzeppelin=lib/openzeppelin-contracts", "@chainlink=lib/chainlink-brownie-contracts", "@uniswap/v2-periphery=lib/v2-periphery"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
